const projects = [
  {
    Title: "Time Tracking Dashboard",
    WebURL: "https://github.com/ivandro-neto/EventHub",
    RepoURL: "---",
    ImageURL: "images/Projects/EventHubAPI.png",
    Description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Hic,
            obcaecati eveniet.Nesciunt a modi,
            ex neque aliquid ratione ut velit sit doloremque,
            laudantium delectus temporibus, ad eum sed debitis exercitationem.`,
  },
  {
    Title: "Math Game",
    WebURL: "https://ivandro-neto.github.io/MathGame/",
    RepoURL: "---",
    ImageURL: "images/Projects/Math Game.png",
    Description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Hic,
            obcaecati eveniet.Nesciunt a modi,
            ex neque aliquid ratione ut velit sit doloremque,
            laudantium delectus temporibus, ad eum sed debitis exercitationem.`,
  },
  {
    Title: "Design Patterns package projects - C#",
    WebURL: "https://github.com/ivandro-neto/Design-Patterns-package-projects---C-",
    RepoURL: "---",
    ImageURL: "images/Projects/default.png",
    Description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Hic,
            obcaecati eveniet.Nesciunt a modi,
            ex neque aliquid ratione ut velit sit doloremque,
            laudantium delectus temporibus, ad eum sed debitis exercitationem.`,
  },
  {
    Title: "Kilunga",
    WebURL: "https://kilunga.netlify.app/",
    RepoURL: "---",
    ImageURL: "images/Projects/kilunga.png",
    Description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Hic,
            obcaecati eveniet.Nesciunt a modi,
            ex neque aliquid ratione ut velit sit doloremque,
            laudantium delectus temporibus, ad eum sed debitis exercitationem.`,
  },
  {
    Title: "Advice Generator App",
    WebURL: "https://ivandro-neto.github.io/advice-generator-app-main/",
    RepoURL: "---",
    ImageURL: "images/Projects/advice.png",
    Description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Hic,
            obcaecati eveniet.Nesciunt a modi,
            ex neque aliquid ratione ut velit sit doloremque,
            laudantium delectus temporibus, ad eum sed debitis exercitationem.`,
  },
  {
    Title: "IN progress project...",
    WebURL: "https://spacium.netlify.app/",
    RepoURL: "---",
    ImageURL: "images/Projects/pending.png",
    Description: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Hic,
            obcaecati eveniet.Nesciunt a modi,
            ex neque aliquid ratione ut velit sit doloremque,
            laudantium delectus temporibus, ad eum sed debitis exercitationem.`,
  },
];
